DROP TABLE IF EXISTS contact;

CREATE TABLE contact (
  id BIGINT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  email VARCHAR(250) DEFAULT NULL,
  company VARCHAR(250) DEFAULT NULL,
  departement VARCHAR(250) DEFAULT NULL
);